version: "3.9"

services:
  travel-planner-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${VITE_PORT:-3000}:3000"
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - default
      - hong_service

networks:
  hong_service:
    external: true
