version: "3.9"

services:
  travel-planner-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://travel-planner-server}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "${VITE_PORT:-3000}:80"
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - default
      - hong_service

networks:
  hong_service:
    external: true
